name: Build and Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-nest-app:latest .

    - name: Push Docker image to DockerHub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/my-nest-app:latest

    - name: Stop and remove old container
      run: |
        docker stop my-nest-app || true
        docker rm my-nest-app || true

    - name: Run new container
      run: |
        docker run -d --name my-nest-app -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/my-nest-app:latest
